### ISSUE TITLE
Latest spec for FHIRPath?

### ISSUE THREAD

**Issue by CarthageKing** [FHIR/fluentpath#3]
Hi,

Will this repository be the place the latest updates to the FHIRPath specification be posted?

We're implementing FHIRPath for constraint validation and started using the specification in https://github.com/ewoutkramer/fhirpath, but that repo is a bit old. We found this repo has the 2017Jan version.

Just wanted to know again if future updates to FHIRPath will be posted to this repo?

**Comment by ewoutkramer** [comment]
Yes - this is the active repo, and I have now removed the old ewoutkramer/fhirpath one.
